#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any


DESCRIPTION_PREFIX = "Use this prompt"
FENCED_BLOCK_RE = re.compile(r"```[^\n]*\n(.*?)\n```", re.DOTALL)


@dataclass(frozen=True)
class RuntimePaths:
    repo_root: Path
    skills_root: Path
    output_dir: Path
    mapping_path: Path


@dataclass(frozen=True)
class AgentMapping:
    role: str
    agent_name: str
    prompt_path: str


class ClaudeAgentSyncError(RuntimeError):
    pass


class ClaudeInvocationError(RuntimeError):
    def __init__(self, message: str, *, returncode: int, stdout: str, stderr: str) -> None:
        super().__init__(message)
        self.returncode = returncode
        self.stdout = stdout
        self.stderr = stderr


def repo_root_from(script_file: Path) -> Path:
    proc = subprocess.run(
        ["git", "-C", str(script_file.parent), "rev-parse", "--show-toplevel"],
        check=True,
        capture_output=True,
        text=True,
    )
    return Path(proc.stdout.strip()).resolve()


def resolve_runtime_paths(script_file: Path) -> RuntimePaths:
    script_file = script_file.resolve()
    repo_root = repo_root_from(script_file)
    script_dir = script_file.parent
    if script_dir.name != "scripts" or script_dir.parent.name != "pm" or script_dir.parent.parent.name != "skills":
        raise ClaudeAgentSyncError(f"Unsupported PM script layout: {script_dir}")
    skills_root = script_dir.parent.parent
    return RuntimePaths(
        repo_root=repo_root,
        skills_root=skills_root,
        output_dir=repo_root / ".claude" / "agents",
        mapping_path=skills_root / "pm" / "agents" / "claude-agent-map.json",
    )


def load_agent_mappings(mapping_path: Path) -> list[AgentMapping]:
    if not mapping_path.is_file():
        raise ClaudeAgentSyncError(f"Claude agent map not found: {mapping_path}")
    try:
        payload = json.loads(mapping_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ClaudeAgentSyncError(f"Invalid Claude agent map JSON: {mapping_path}: {exc}") from exc
    if not isinstance(payload, list):
        raise ClaudeAgentSyncError(f"Claude agent map must be a JSON array: {mapping_path}")
    mappings: list[AgentMapping] = []
    for entry in payload:
        if not isinstance(entry, dict):
            raise ClaudeAgentSyncError(f"Claude agent map entry must be an object: {entry!r}")
        try:
            mapping = AgentMapping(
                role=str(entry["role"]),
                agent_name=str(entry["agent_name"]),
                prompt_path=str(entry["prompt_path"]),
            )
        except KeyError as exc:
            raise ClaudeAgentSyncError(f"Missing Claude agent map key: {exc.args[0]}") from exc
        mappings.append(mapping)
    if not mappings:
        raise ClaudeAgentSyncError(f"Claude agent map is empty: {mapping_path}")
    return mappings


def normalize_single_line(value: str) -> str:
    return " ".join(value.strip().split())


def extract_source_description(source_text: str, source_path: Path) -> str:
    for raw_line in source_text.splitlines():
        line = raw_line.strip()
        if line.startswith(DESCRIPTION_PREFIX):
            return normalize_single_line(line)
    raise ClaudeAgentSyncError(f"Missing '{DESCRIPTION_PREFIX}' line in {source_path}")


def extract_source_prompt(source_text: str, source_path: Path) -> str:
    match = FENCED_BLOCK_RE.search(source_text)
    if not match:
        raise ClaudeAgentSyncError(f"Missing fenced prompt block in {source_path}")
    return match.group(1).strip() + "\n"


def build_agent_markdown(mapping: AgentMapping, relative_source_path: str, source_text: str) -> str:
    description = extract_source_description(source_text, Path(relative_source_path))
    prompt = extract_source_prompt(source_text, Path(relative_source_path))
    generated_header = (
        f"<!-- Generated by sync-claude-agents.py from {relative_source_path} "
        f"for orchestrator role {mapping.role}. Do not edit directly. -->"
    )
    return (
        "---\n"
        f"name: {json.dumps(mapping.agent_name)}\n"
        f"description: {json.dumps(description)}\n"
        "---\n\n"
        f"{generated_header}\n\n"
        f"{prompt}"
    )


def render_expected_agents(paths: RuntimePaths) -> dict[str, dict[str, Any]]:
    expected: dict[str, dict[str, Any]] = {}
    for mapping in load_agent_mappings(paths.mapping_path):
        source_path = paths.skills_root / mapping.prompt_path
        if not source_path.is_file():
            raise ClaudeAgentSyncError(f"Prompt source not found for role {mapping.role}: {source_path}")
        relative_output_path = Path(".claude") / "agents" / f"{mapping.agent_name}.md"
        content = build_agent_markdown(
            mapping=mapping,
            relative_source_path=mapping.prompt_path,
            source_text=source_path.read_text(encoding="utf-8"),
        )
        expected[mapping.role] = {
            "role": mapping.role,
            "agent_name": mapping.agent_name,
            "prompt_path": mapping.prompt_path,
            "output_path": paths.repo_root / relative_output_path,
            "relative_output_path": relative_output_path.as_posix(),
            "content": content,
            "description": extract_source_description(source_path.read_text(encoding="utf-8"), source_path),
        }
    return expected


def sync_agents(paths: RuntimePaths, *, check: bool = False) -> dict[str, list[str]]:
    expected = render_expected_agents(paths)
    created: list[str] = []
    updated: list[str] = []
    unchanged: list[str] = []
    removed: list[str] = []
    drift: list[str] = []
    expected_paths = {item["relative_output_path"] for item in expected.values()}

    if not check:
        paths.output_dir.mkdir(parents=True, exist_ok=True)

    if paths.output_dir.exists():
        for existing in sorted(paths.output_dir.glob("pm-*.md")):
            relative_output_path = (Path(".claude") / "agents" / existing.name).as_posix()
            if relative_output_path in expected_paths:
                continue
            if check:
                drift.append(f"unexpected:{relative_output_path}")
            else:
                existing.unlink()
                removed.append(relative_output_path)

    for item in expected.values():
        output_path = item["output_path"]
        relative_output_path = item["relative_output_path"]
        content = item["content"]
        if not output_path.exists():
            if check:
                drift.append(f"missing:{relative_output_path}")
            else:
                output_path.write_text(content, encoding="utf-8")
                created.append(relative_output_path)
            continue
        current = output_path.read_text(encoding="utf-8")
        if current != content:
            if check:
                drift.append(f"stale:{relative_output_path}")
            else:
                output_path.write_text(content, encoding="utf-8")
                updated.append(relative_output_path)
            continue
        unchanged.append(relative_output_path)

    return {
        "created": created,
        "updated": updated,
        "unchanged": unchanged,
        "removed": removed,
        "drift": drift,
    }


def sync_counts(sync_summary: dict[str, list[str]]) -> dict[str, int]:
    return {key: len(value) for key, value in sync_summary.items()}


def mapping_for_role(paths: RuntimePaths, role: str) -> dict[str, Any]:
    expected = render_expected_agents(paths)
    try:
        return expected[role]
    except KeyError as exc:
        available = ", ".join(sorted(expected))
        raise ClaudeAgentSyncError(f"Unknown Claude agent role '{role}'. Available roles: {available}") from exc


def resolve_claude_command() -> str:
    command_name = os.environ.get("CLAUDE_COMMAND", "claude")
    if "/" in command_name:
        command_path = Path(command_name)
        if not command_path.is_file() or not os.access(command_path, os.X_OK):
            raise ClaudeAgentSyncError(f"Configured Claude command is not executable: {command_name}")
        return str(command_path)
    resolved = shutil.which(command_name)
    if not resolved:
        raise ClaudeAgentSyncError(f"Claude command is not executable in PATH: {command_name}")
    return resolved


def run_claude_agent(
    script_file: Path,
    *,
    role: str,
    prompt: str,
    session_id: str | None = None,
    cwd: str | None = None,
    agent_type: str | None = None,
) -> dict[str, Any]:
    if not prompt.strip():
        raise ClaudeAgentSyncError("Prompt must not be empty")
    if agent_type and agent_type not in {"default", "explorer", "worker"}:
        raise ClaudeAgentSyncError(f"Unsupported agent_type '{agent_type}'. Expected default, explorer, or worker.")

    paths = resolve_runtime_paths(script_file)
    sync_summary = sync_agents(paths, check=False)
    agent = mapping_for_role(paths, role)
    working_directory = Path(cwd).resolve() if cwd else paths.repo_root
    command = [resolve_claude_command(), "-p", "--agent", agent["agent_name"]]
    if session_id:
        command.extend(["--session-id", session_id])
    command.append(prompt)
    proc = subprocess.run(
        command,
        cwd=working_directory,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise ClaudeInvocationError(
            (
                f"Claude agent invocation failed for role {role} using agent {agent['agent_name']}. "
                f"stdout={normalize_single_line(proc.stdout)} stderr={normalize_single_line(proc.stderr)}"
            ),
            returncode=proc.returncode,
            stdout=proc.stdout,
            stderr=proc.stderr,
        )
    return {
        "role": role,
        "agent_name": agent["agent_name"],
        "agent_type": agent_type or "",
        "prompt_path": agent["prompt_path"],
        "cwd": str(working_directory),
        "response": proc.stdout.strip(),
        "sync": sync_counts(sync_summary),
    }
